"""
Django settings for backchat project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import parse_qsl, unquote, urlparse


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def env_int(name, default):
    value = os.getenv(name)
    if value is None or not value.strip():
        return default
    return int(value)


def env_list(name, default=None):
    value = os.getenv(name)
    if value is None:
        return list(default or [])
    return [item.strip() for item in value.split(',') if item.strip()]


def env_str(name, default=''):
    value = os.getenv(name)
    if value is None:
        return default

    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        value = value[1:-1].strip()

    if not value or value.lower() in {'none', 'null'}:
        return default

    # Ignore unresolved placeholders like ${DATABASE_URL} from deploy settings.
    if value.startswith('${') and value.endswith('}'):
        return default

    return value

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def database_config():
    database_url = env_str('DATABASE_URL', '')
    if database_url:
        parsed = urlparse(database_url)
        engine_map = {
            'postgres': 'django.db.backends.postgresql',
            'postgresql': 'django.db.backends.postgresql',
            'pgsql': 'django.db.backends.postgresql',
            'sqlite': 'django.db.backends.sqlite3',
            'sqlite3': 'django.db.backends.sqlite3',
        }
        engine = engine_map.get(parsed.scheme.lower())
        if engine is None:
            if not parsed.scheme:
                database_url = ''
            else:
                raise ValueError(f'Unsupported DATABASE_URL scheme: {parsed.scheme}')
        elif engine == 'django.db.backends.sqlite3':
            sqlite_name = unquote(parsed.path.lstrip('/')) or 'db.sqlite3'
            sqlite_path = Path(sqlite_name)
            return {
                'ENGINE': engine,
                'NAME': sqlite_path if sqlite_path.is_absolute() else BASE_DIR / sqlite_path,
            }
        else:
            options = dict(parse_qsl(parsed.query, keep_blank_values=True))
            config = {
                'ENGINE': engine,
                'NAME': unquote(parsed.path.lstrip('/')),
                'USER': unquote(parsed.username or ''),
                'PASSWORD': unquote(parsed.password or ''),
                'HOST': parsed.hostname or 'localhost',
                'PORT': str(parsed.port or '5432'),
                'CONN_MAX_AGE': env_int('DB_CONN_MAX_AGE', 60),
                'CONN_HEALTH_CHECKS': True,
            }
            if options:
                config['OPTIONS'] = options

            sslmode = os.getenv('POSTGRES_SSLMODE')
            if sslmode:
                config.setdefault('OPTIONS', {})['sslmode'] = sslmode
            return config

    if os.getenv('POSTGRES_DB'):
        config = {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB', ''),
            'USER': os.getenv('POSTGRES_USER', ''),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', ''),
            'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
            'PORT': os.getenv('POSTGRES_PORT', '5432'),
            'CONN_MAX_AGE': env_int('DB_CONN_MAX_AGE', 60),
            'CONN_HEALTH_CHECKS': True,
        }
        sslmode = os.getenv('POSTGRES_SSLMODE')
        if sslmode:
            config['OPTIONS'] = {'sslmode': sslmode}
        return config

    return {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'SECRET_KEY',
    'django-insecure-$h$lo7+yzmkee#^mdr%qzgova9b8^y+w9(-u46j4o%ebl-i#z!',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', True)

ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', ['localhost', '127.0.0.1'])
for deploy_host_var in ('RENDER_EXTERNAL_HOSTNAME', 'RAILWAY_PUBLIC_DOMAIN'):
    deploy_host = os.getenv(deploy_host_var)
    if deploy_host and deploy_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(deploy_host)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'channels',
    'chatsecure',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backchat.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backchat.wsgi.application'
ASGI_APPLICATION = 'backchat.asgi.application'

# Channels (in-memory layer by default; configure Redis in production)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

# Django REST Framework basic setup (extend as needed)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'chatsecure.auth.CsrfExemptSessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# CORS (allow all in dev; tighten for prod)
_default_frontend_origins = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'https://chatsegur.netlify.app',
]
CORS_ALLOW_ALL_ORIGINS = env_bool('CORS_ALLOW_ALL_ORIGINS', False)
CORS_ALLOWED_ORIGINS = env_list('CORS_ALLOWED_ORIGINS', _default_frontend_origins)
CORS_ALLOW_CREDENTIALS = env_bool('CORS_ALLOW_CREDENTIALS', True)

CSRF_TRUSTED_ORIGINS = env_list('CSRF_TRUSTED_ORIGINS', CORS_ALLOWED_ORIGINS)


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': database_config(),
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.getenv('TIME_ZONE', 'UTC')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Use BigAutoField for primary keys
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Compat: Django 4.2 on Python 3.14 (BaseContext.__copy__ bug) ---
# Django 4.2 não oferece suporte oficial a Python 3.14 e a implementação
# padrão usa copy(super()), que quebra em 3.14. Fazemos monkey-patch
# que preserva os atributos que o admin espera (template, render_context etc.).
from copy import copy as _copy  # noqa: E402
from django.template import context as _dj_context  # noqa: E402


def _safe_basecontext_copy(self):
    dup = object.__new__(self.__class__)
    dup.dicts = list(self.dicts)

    # Copia atributos usados durante renderização de templates/admin
    if hasattr(self, 'render_context'):
        dup.render_context = _copy(self.render_context)
    dup.template = getattr(self, 'template', None)
    dup.template_name = getattr(self, 'template_name', 'unknown')

    for attr in (
        'autoescape',
        'use_l10n',
        'use_tz',
        '_processors',
        '_processors_index',
        'request',
    ):
        if hasattr(self, attr):
            setattr(dup, attr, getattr(self, attr))

    return dup


_dj_context.BaseContext.__copy__ = _safe_basecontext_copy
