# Generated by Django 4.2.7 on 2026-03-19 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da CA', max_length=100)),
                ('ca_public_key', models.TextField(help_text='Chave pública da CA')),
                ('ca_private_key', models.TextField(help_text='Chave privada da CA (criptografada)')),
                ('ca_certificate', models.TextField(help_text='Certificado autoassinado da CA')),
                ('is_root', models.BooleanField(default=True, help_text='É CA raiz?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_type', models.CharField(choices=[('private', 'Privada (1-1)'), ('group', 'Grupo')], default='private', max_length=10)),
                ('group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('group_public_key', models.TextField(blank=True, help_text='Chave pública do grupo (para grupos)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participants', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_content', models.TextField(help_text='Conteúdo criptografado com chave simétrica')),
                ('encrypted_session_key', models.TextField(help_text='Chave de sessão (simétrica) criptografada com chave pública do destinatário')),
                ('digital_signature', models.TextField(help_text='Assinatura RSA do hash da mensagem')),
                ('hash_algorithm', models.CharField(choices=[('sha256', 'SHA-256'), ('sha512', 'SHA-512'), ('sha3_256', 'SHA3-256'), ('sha3_512', 'SHA3-512')], default='sha256', max_length=20)),
                ('message_hash', models.TextField(help_text='Hash da mensagem original para verificação de integridade')),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('file', 'Arquivo')], default='text', max_length=10)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatsecure.conversation')),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key_rsa', models.TextField(help_text='Chave pública RSA (formato PEM)')),
                ('private_key_rsa', models.TextField(help_text='Chave privada RSA (criptografada)')),
                ('dh_public_key', models.TextField(blank=True, help_text='Chave pública DH', null=True)),
                ('dh_private_key', models.TextField(blank=True, help_text='Chave privada DH (criptografada)', null=True)),
                ('dh_prime', models.TextField(blank=True, help_text='Número primo P para DH', null=True)),
                ('dh_generator', models.TextField(blank=True, help_text='Gerador G para DH', null=True)),
                ('certificate', models.TextField(blank=True, help_text='Certificado digital X.509', null=True)),
                ('certificate_issuer', models.CharField(blank=True, help_text='Emissor do certificado', max_length=255)),
                ('certificate_valid_from', models.DateTimeField(blank=True, null=True)),
                ('certificate_valid_to', models.DateTimeField(blank=True, null=True)),
                ('certificate_serial', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RevokedCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_serial', models.CharField(max_length=100)),
                ('revoked_at', models.DateTimeField(auto_now_add=True)),
                ('revocation_reason', models.TextField()),
                ('revoked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatsecure.certificateauthority')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatsecure.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='KeyExchangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_type', models.CharField(choices=[('rsa', 'Troca RSA'), ('dh', 'Diffie-Hellman'), ('hybrid', 'Híbrido (PGP)')], max_length=10)),
                ('parameters_used', models.JSONField(help_text='Parâmetros usados na troca (primos, geradores, etc)')),
                ('status', models.CharField(choices=[('success', 'Sucesso'), ('failure', 'Falha'), ('pending', 'Pendente')], max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_exchanges_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_exchanges_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SharedKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_shared_key', models.TextField(help_text='Chave compartilhada criptografada')),
                ('key_size', models.IntegerField(default=128, help_text='Tamanho da chave em bits (PRNG)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('hash_algorithm', models.CharField(choices=[('sha256', 'SHA-256'), ('sha512', 'SHA-512'), ('sha3', 'SHA-3')], default='sha256', max_length=10)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_keys_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_keys_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user1', 'user2')},
            },
        ),
        migrations.CreateModel(
            name='SessionKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key_encrypted', models.TextField(help_text='Chave de sessão criptografada com chave pública')),
                ('dh_shared_secret', models.TextField(blank=True, help_text='Segredo compartilhado DH (criptografado)')),
                ('dh_prime_used', models.TextField(help_text='Primo P usado na troca DH')),
                ('dh_generator_used', models.TextField(help_text='Gerador G usado na troca DH')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Data de expiração da chave de sessão')),
                ('is_active', models.BooleanField(default=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user1', 'user2', 'is_active')},
            },
        ),
        migrations.CreateModel(
            name='MessageDeliveryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', 'Enviada'), ('delivered', 'Entregue'), ('read', 'Lida'), ('failed', 'Falhou')], default='sent', max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('individual_session_key', models.TextField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_status', to='chatsecure.message')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('message', 'recipient')},
            },
        ),
    ]
